In [1]:
# numpy and pandas for data manipulation
import numpy as np
import pandas as pd 

# sklearn preprocessing for dealing with categorical variables
from sklearn.preprocessing import LabelEncoder

# File system manangement
import os

# Suppress warnings 
import warnings
warnings.filterwarnings('ignore')

# matplotlib and seaborn for plotting
import matplotlib.pyplot as plt
import seaborn as sns

# [Problem 1] Cross Validation

In [2]:
app_train = pd.read_csv('application_train.csv')
app_train.head()

SK_ID_CURR  TARGET  ... AMT_REQ_CREDIT_BUREAU_QRT AMT_REQ_CREDIT_BUREAU_YEAR
0      100002       1  ...                       0.0                        1.0
1      100003       0  ...                       0.0                        0.0
2      100004       0  ...                       0.0                        0.0
3      100006       0  ...                       NaN                        NaN
4      100007       0  ...                       0.0                        0.0

[5 rows x 122 columns]

In [3]:
le = LabelEncoder()
le_count = 0

for col in app_train:
    if app_train[col].dtypes == 'object':        
        if len(list(app_train[col].unique())) <= 2:
            le.fit(app_train[col])
            app_train[col] = le.transform(app_train[col])  
            le_count += 1

print('{} columns are label encoded.'.format(le_count))     

3 columns are label encoded.


In [4]:
app_train = pd.get_dummies(app_train)

print('Training data shape: {}'.format(app_train.shape))

Training data shape: (307511, 243)


In [5]:
y = app_train['TARGET'].values
y

array([1, 0, 0, ..., 0, 1, 0])

In [6]:
x = app_train[['DAYS_BIRTH', 'DAYS_EMPLOYED']].values
x

array([[ -9461,   -637],
       [-16765,  -1188],
       [-19046,   -225],
       ...,
       [-14966,  -7921],
       [-11961,  -4786],
       [-16856,  -1262]])

In [7]:
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

kf = KFold(n_splits=5, shuffle=True)

i = 1
for train_idx, test_idx in kf.split(x):
    x_train, x_test = x[train_idx], x[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    scaler  = StandardScaler().fit(x_train)
    x_train = scaler.transform(x_train)
    x_test  = scaler.transform(x_test)

    cf = DecisionTreeClassifier().fit(x_train, y_train)
    y_pred = cf.predict(x_test)

    p1 = cf.score(x_train, y_train)
    p2 = cf.score(x_test, y_test)

    print('Sample {}:\n- Train Score {}\n- Test Score {}'.format(i, p1, p2))

Sample 1:
- Train Score 0.9905897369191246
- Test Score 0.8596816415459408
Sample 1:
- Train Score 0.9908255389030483
- Test Score 0.8588988975968261
Sample 1:
- Train Score 0.9907808250917649
- Test Score 0.8571916360443563
Sample 1:
- Train Score 0.9906588783337195
- Test Score 0.8548665084062307
Sample 1:
- Train Score 0.9906913974691983
- Test Score 0.8569640011706936


In [8]:
#Get score with cross_val_score
from sklearn.model_selection import cross_val_score

print(cross_val_score(DecisionTreeClassifier(), x, y, cv=5, n_jobs=-1))

[0.85672244 0.85678515 0.85782576 0.85894768 0.85554941]


# [Problem 2] Grid search

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.75, test_size=0.25)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(230633, 2) (76878, 2) (230633,) (76878,)


In [10]:
scaler  = StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)
x_test  = scaler.transform(x_test)

In [11]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_neighbors': np.arange(1, 20),
    'metric': ['euclidean', 'manhattan', 'minkowski']
}

grid = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, n_jobs=-1)
grid.fit(x_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [12]:
grid.best_score_

0.9189144657741208

In [13]:
grid.best_params_

{'metric': 'manhattan', 'n_neighbors': 18}

In [14]:
model = grid.best_estimator_

In [15]:
model.score(x_test, y_test)

0.9203283123910612

# [Problem 3] Survey from Kaggle Notebooks


After looking at several Kaggel Notebooks, here is the lists of used methods:
*   XGBClassifier(n_estimators=500, max_depth=8, random_state=2018)
*   LogisticRegression(C = 0.0001)
*   RandomForestClassifier(n_estimators=128, random_state=42, n_jobs=-1)




# [Problem 4] Creating a model with high generalization performance

In [16]:
param_grid = {'random_state': [500, 1000, 2000, 2500]}
grid_random = GridSearchCV(RandomForestClassifier(n_estimators=50), param_grid, cv=5, n_jobs=-1)
grid_random.fit(x_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=50, n_jobs=None,
                                              oob_score=False,
                                              random

In [17]:
grid_random.best_score_

0.911391688581516

In [18]:
grid_random.best_params_

{'random_state': 1000}

In [19]:
grid_random = grid_random.best_estimator_

In [20]:
grid_random.score(x_test, y_test)

0.9133692343713417

# [Problem 5] Final model selection

After having commited to kaggle, here are my score:



1.   KNeigborClassifier
    *   Private score: 0.53271
    *   Public score: 0.52680
2.   RandomForestClassifier
    *   Private score: 0.53145
    *   Public score: 0.53691

Kaggle link: https://www.kaggle.com/theciderizer/home-credit <br>
According to the above scores, we need to have better features selection in order to improve.

