# [Problem 1] Enumeration of classes used so far



*   StandardScaler
*   DataFrame
*   LinearRegression
*   KNeighborsClassifier
...




In [1]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from math import sqrt

X, y = load_iris(return_X_y=True)

scaler = StandardScaler()
scaler.fit(X)


print("Mean: {}\nStd:  {}".format(scaler.mean_, list(map(sqrt, scaler.var_))))

Mean: [5.84333333 3.05733333 3.758      1.19933333]
Std:  [0.8253012917851409, 0.43441096773549437, 1.7594040657753032, 0.7596926279021594]


# [Problem 2] Enumeration of methods and instance variables used so far


Instance:


*   pandas.DataFrame.size
*   pandas.DataFrame.columns
*   pandas.DataFrame.index
*   sklearn.preprocessing.StandardScaler.mean_
*   sklearn.preprocessing.StandardScaler.var_



Method:

*   pandas.concat
*   numpy.hstack
*   numpy.concatenate
*   sklearn.linear_model.LinearRegression.fit
*   sklearn.linear_model.LinearRegression.predict


In [2]:
X_std = scaler.transform(X)
X_std

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

# [Problem 3] Creating a standardized class by scratch

In [3]:
import numpy as np

class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        mean = np.array([self.mean_,] * X.shape[0])
        std = np.array([np.sqrt(self.var_),] * X.shape[0])
        X_scaled = (X - mean) / std
        return X_scaled

In [4]:
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# [Problem 4] Creating a class that performs 4 arithmetic operations

In [5]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))

    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    
    def sub(self, value2):
        """
        Substract self with value 2
        """
        self.value -= value2

    def mul(self, value2):
        """
        Multiply self with value 2
        """
        self.value *= value2

    def div(self, value2):
        """
        Divide self with value 2
        """
        try:
            self.value /= value2
        except:
            raise Exception("Zero division")

example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.mul(3)
print("value : {}".format(example.value))
example.div(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8
value : 24
value : 8.0
