In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

[Problem 1] Matrix product is calculated manually

C = A . B <br>
$C_{11}$ = (-1) * 0 + 2 * 0 + 3 * 2 = 6 <br>
$C_{12}$ = (-1) * 2 + 2 * 2 + 3 * 9 = 29 <br>
$C_{13}$ = (-1) * 1 + 2 * (-8) + 3 * -1 = -20 <br>

$C_{21}$ = 4 * 0 - 5 * 0 + 6 * 2 = 12 <br>
$C_{22}$ = 4 * 2 - 5 * 2 + 6 * 9 = 52 <br>
$C_{23}$ = 4 * 1 - 5 * (-8) + 6 * -1 = 38 <br>

$C_{31}$ = 7 * 0 + 8 * 0 - 9 * 2 = -18 <br>
$C_{32}$ = 7 * 2 + 8 * 2 - 9 * 9 = -51 <br>
$C_{33}$ = 7 * 1 + 8 * (-8) - 9 * (-1) = -48 <br>

==> C = [[6, 29, -20], [12, 52, 38], [-18, -51, -48]]        

[Problem 2] Calculation by Numpy function

In [2]:
c = np.matmul(a_ndarray, b_ndarray)
print(c)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


[Problem 3] Implementation of calculation of a certain element

In [3]:
total = np.sum(a_ndarray[0, :] * b_ndarray[:, 0])
print(total)

6


[Problem 4 & 5] Creating a function that performs matrix multiplication and judge the input whose calculation is not defined

In [4]:
def dotProduct(a, b):
    """
    calculate dot product of two matrices
    ------------
    Parameters
    a, b: matrix
    ------------
    Return
    Production matrix from a and b    
    """
    if a.shape[1] != b.shape[0]:
        print("Number of columns of matrix a and number of rows of matrix b are not the same!")        
    else:
        result = []
        for i in range(a.shape[0]):
            for j in range(b.shape[1]):
                result.append(np.sum(a[i, :] * b[:, j]))                
        result = np.array(result).reshape(a.shape[0], b.shape[1])
        return result

tmp = dotProduct(a_ndarray, b_ndarray)
print(tmp)
#--------------------------------------
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
tmp = dotProduct(d_ndarray_, e_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Number of columns of matrix a and number of rows of matrix b are not the same!


[Problem 6] Tranposition

In [5]:
tmp = dotProduct(d_ndarray_, e_ndarray.T)
print(tmp)

[[ 46  -4]
 [-34  73]]
